
name: 'lokalise_dbt'
version: '1.0.0'

profile: 'lokalise_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  main_cast: 5
  lookback_timeframe_days: 600

models:
  lokalise_dbt:

    staging:
      +materialized: view
